#define TK_LC                              1
#define TK_RC                              2
#define TK_FORMAT                          3
#define TK_OR                              4
#define TK_AND                             5
#define TK_NOT                             6
#define TK_LIKE                            7
#define TK_MATCH                           8
#define TK_NE                              9
#define TK_EQ                             10
#define TK_REMOVE                         11
#define TK_GT                             12
#define TK_LE                             13
#define TK_LT                             14
#define TK_GE                             15
#define TK_ESCAPE                         16
#define TK_BITAND                         17
#define TK_BITOR                          18
#define TK_LSHIFT                         19
#define TK_RSHIFT                         20
#define TK_PLUS                           21
#define TK_MINUS                          22
#define TK_STAR                           23
#define TK_SLASH                          24
#define TK_MODULUS                        25
#define TK_REM                            26
#define TK_CONCAT                         27
#define TK_IF                             28
#define TK_THEN                           29
#define TK_ELSE                           30
#define TK_UMINUS                         31
#define TK_UPLUS                          32
#define TK_BITNOT                         33
#define TK_LP                             34
#define TK_RP                             35
#define TK_INTEGER_PARAM                  36
#define TK_HASH                           37
#define TK_AT                             38
#define TK_TOTAL                          39
#define TK_COUNT                          40
#define TK_MIN                            41
#define TK_COMMA                          42
#define TK_MAX                            43
#define TK_ABS                            44
#define TK_EVAL                           45
#define TK_INTEGER                        46
#define TK_INTEGER_GLOBAL                 47
#define TK_ATOI                           48
#define TK_STRING                         49
#define TK_STRING_PARAM                   50
#define TK_PRINT                          51
#define TK_RUN                            52
#define TK_SUM                            53
#define TK_COLUMN                         54
#define TK_LB                             55
#define TK_RB                             56
#define TK_COLUMN_S                       57
#define TK_GS                             58
#define TK_PS                             59
#define TK_T                              60
#define TK_SHADER                         61
#define TK_SOUND                          62
#define TK_PORTRAIT                       63
#define TK_MODEL                          64
#define TK_RND                            65
#define TK_SYS_TIME                       66
