code

equ	trap_Print							-1
equ	trap_Error							-2
equ	trap_Milliseconds					-3
equ	trap_Cvar_Register					-4
equ	trap_Cvar_Update					-5
equ	trap_Cvar_Set						-6
equ trap_Cvar_VariableStringBuffer		-7
equ	trap_Argc							-8
equ	trap_Argv							-9
equ trap_ArgvI							-10
equ	trap_Args							-11
equ trap_Cmd_ExecuteText				-12
equ	trap_FS_FOpenFile					-13
equ	trap_FS_Read						-14
equ	trap_FS_Write						-15 
equ	trap_FS_FCloseFile					-16
equ	trap_SendConsoleCommand				-17
equ trap_ForwardCommand					-18
equ	trap_AddCommand						-19
equ	trap_SendClientCommand				-20
equ	trap_UpdateScreen					-21
equ	trap_CM_LoadMap						-22
equ	trap_CM_NumInlineModels				-23
equ	trap_CM_InlineModel					-24
equ	trap_CM_LoadModel					-25
equ	trap_CM_TempBoxModel				-26
equ	trap_CM_PointContents				-27
equ	trap_CM_TransformedPointContents	-28
equ	trap_CM_BoxTrace					-29
equ	trap_CM_TransformedBoxTrace			-30
equ	trap_CM_MarkFragments				-31
equ	trap_S_StartSound					-32
equ	trap_S_StartLocalSound				-33
equ	trap_S_ClearLoopingSounds			-34
equ	trap_S_AddLoopingSound				-35
equ	trap_S_UpdateEntityPosition			-36
equ	trap_S_Respatialize					-37
equ	trap_S_RegisterSound				-38
equ	trap_S_StartBackgroundTrack			-39
equ	trap_R_LoadWorldMap					-40
equ	trap_R_RegisterModel				-41
equ	trap_R_RegisterSkin					-42
equ	trap_R_RegisterShader				-43
equ	trap_R_ClearScene					-44
equ trap_R_BuildPose					-45
equ trap_R_BuildPose2					-46
equ trap_R_BuildPose3					-47
equ trap_R_LerpTagFromPose				-48
equ	trap_R_AddRefEntityToScene			-49
equ	trap_R_AddPolyToScene				-50
equ	trap_R_AddLightToScene				-51
equ	trap_R_RenderScene					-52
equ	trap_R_SetColor						-53
equ	trap_R_DrawStretchPic				-54
equ	trap_R_ShapeCreate					-55
equ	trap_R_ShapeDraw					-56
equ	trap_R_DrawText						-57
equ	trap_R_GetFont						-58
equ	trap_R_RoundRect					-59
equ	trap_R_ModelBounds					-60
equ	trap_R_LerpTag						-61
equ	trap_GetGlconfig					-62
equ	trap_GetGameState					-63
equ	trap_GetCurrentSnapshotNumber		-64
equ	trap_GetSnapshot					-65
equ	trap_GetServerCommand				-66
equ	trap_GetCurrentCmdNumber			-67
equ	trap_GetUserCmd						-68
equ	trap_SetUserCmdValue				-69
equ	trap_R_RegisterShaderNoMip			-70
equ	trap_MemoryRemaining				-71
equ trap_R_RegisterFont					-72
equ trap_Key_IsDown						-73
equ trap_Key_GetCatcher					-74
equ trap_Key_SetCatcher					-75
equ trap_Key_GetKey						-76
equ trap_PC_AddGlobalDefine				-77
equ	trap_PC_LoadSource					-78
equ trap_PC_FreeSource					-79
equ trap_PC_ReadToken					-80
equ trap_PC_SourceFileAndLine			-81
equ trap_S_StopBackgroundTrack			-82
equ trap_RealTime						-83
equ trap_SnapVector						-84
equ trap_UpdateGameState				-85
equ trap_RemoveCommand					-86
equ trap_R_LightForPoint				-87
equ trap_CIN_PlayCinematic				-88
equ trap_CIN_StopCinematic				-89
equ trap_CIN_RunCinematic 				-90
equ trap_CIN_DrawCinematic				-91
equ trap_CIN_SetExtents					-92
equ trap_R_RemapShader					-93
equ	trap_S_AddRealLoopingSound			-94
equ trap_S_StopLoopingSound				-95
equ trap_CM_TempCapsuleModel			-96
equ trap_CM_CapsuleTrace				-97
equ trap_CM_TransformedCapsuleTrace		-98
equ trap_R_AddAdditiveLightToScene		-99
equ trap_GetEntityToken					-100
equ	trap_R_AddPolysToScene				-101
equ trap_R_inPVS						-102
equ	trap_R_MenuBeginSurf				-103
equ trap_R_MenuEndSurf					-104

equ	memset								-105
equ	memcpy								-106
equ	strncpy								-107
equ	sin									-108
equ	cos									-109
equ	atan2								-110
equ	sqrt								-111
equ floor								-112
equ	ceil								-113
equ acos								-114
equ	fmod								-115
equ	pow									-116
equ atan								-117
equ tan									-118
equ	testPrintInt						-119
equ	testPrintFloat						-120

equ Q_rand						-501

equ trap_SQL_LoadDB				-601
equ trap_SQL_Exec				-602
equ trap_SQL_Prepare			-603
equ trap_SQL_Bind				-604
equ trap_SQL_BindText			-605
equ trap_SQL_BindInt			-606
equ trap_SQL_BindArgs			-607
equ trap_SQL_Step				-608
equ trap_SQL_ColumnCount		-609
equ trap_SQL_ColumnAsText		-610
equ trap_SQL_ColumnAsInt		-611
equ trap_SQL_ColumnName			-612
equ trap_SQL_Done				-613
equ trap_SQL_Compile			-614
equ trap_SQL_Run				-615
